version: "3.8"

services:
  homepage-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: root
      POSTGRES_DB: cms
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
 
  homepage-cms:
    build:
      context: ./cms
      dockerfile: Dockerfile
    ports:
      - 1337:1337
    environment:
      - DATABASE_HOST=homepage_homepage-db_1
      - ADMIN_JWT_SECRET=Nx0jXXjG2yFpNVAvhuLcsA==

volumes:
  postgres-data:
